networks:
  icontainer-network:
    external: true

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    networks:
      - icontainer-network
    ports:
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Entrypoints
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=websecure"
      - "--certificatesresolvers.le.acme.email=ti.transtl@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"

      # MÃ©tricas Traefik
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entrypoints.metrics.address=:8082"

      # Dashboard
      - "--api.dashboard=true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certificates:/acme.json

    labels:
      - "traefik.enable=true"

      # Traefik dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.lftecnologia.dev`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    networks:
      - icontainer-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.lftecnologia.dev`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=le"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    restart: always
    networks:
      - icontainer-network
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.lftecnologia.dev`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=le"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

volumes:
  traefik_certificates:
  postgres_data:
  app_data:
  prometheus_data:
  grafana_data:
